name: Reusable workflow deploy job
on: workflow_call
jobs:
    deploy:
        runs-on: ubutu-latest
        steps:
            - name: Output info
              run: echo "The output of my reusable workflow is so amazing"   