name: Reusable workflow deploy job
on: 
    workflow_call:
       inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubutu-latest
        steps:
            - name: Get artifact
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output info
              run: echo "The output of my reusable workflow is so amazing"   